apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth-service
  labels:
    app: user-auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-auth-service
  template:
    spec:
      containers:
      - name: user-auth-service
        image: me-west1-docker.pkg.dev/koala-ops-demo-373407/koala-repo/user-auth-service:latest
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 500Mi
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: user-auth-service-configmap
    metadata:
      labels:
        app: user-auth-service
