apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: user-auth-service
configMapGenerator:
- envs:
  - .env
  name: user-auth-service-configmap
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- podmonitoring.yaml
