apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: user-auth-service-podmonitoring
spec:
  selector:
    matchLabels:
      app: user-auth-service
  endpoints:
  - interval: 30s
    port: 8080
    path: /metrics
    scheme: http