# Build container image and push to registry

name: Build Image & Push to Registry

on:
  workflow_call:
    inputs:
      tag:
        description: "The image tag to use"
        required: true
        type: string
      ref:
        description: "The git ref to use"
        required: false
        type: string
    outputs:
      tag:
        description: "The tag used in practice. If the input tag is empty, determined by branch."
        value: ${{ jobs.build.outputs.tag }}
  workflow_dispatch:
    inputs:
      tag:
        description: "The image tag to use, leave empty to use branch default"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: "me-west1-docker.pkg.dev/koala-ops-demo-373407/koala-repo/user-auth-service"
    outputs:
      tag: ${{ steps.image_tag.outputs.tag }}
    permissions:
      contents: "write"
      id-token: "write"
      packages: "write"

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Determine image tag
        id: image_tag
        run: |
          if [ -n "${{ inputs.tag }}" ]; then
            TAG=$(echo "${{ inputs.tag }}" | tr '/:' '_')
          else
            if [ -n "${{ github.event.pull_request.head.ref }}" ]; then
                BRANCH=${{ github.event.pull_request.head.ref }}
            else
                BRANCH=$(echo "${{ github.ref }}" | sed 's#refs/heads/##')
            fi
            echo "Branch Name: $BRANCH"
            BRANCH=$(echo $BRANCH | tr '/' '_')
            echo "Tag prefix: $BRANCH"
            DATE=$(date +'%Y-%m-%d')
            COUNTER=$(git ls-remote --tags | grep ${BRANCH}_${DATE} | wc -l | tr -d ' ')
            TAG=${BRANCH}_${DATE}_${COUNTER}
          fi
          echo "Tag: $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "TAG=$TAG" >> "$GITHUB_OUTPUT"

      - uses: ./.github/actions/build
        name: Build

        # Build & Tag
      - name: Docker build & tag
        run: docker build -t $IMAGE:latest -t $IMAGE:$TAG .
      
        # Login to Docker registry
        # https://cloud.google.com/artifact-registry/docs/docker/authentication#json-key
        # https://github.com/docker/login-action#service-account-based-authentication-1
      - name: Login to GCP Docker Image Registry
        uses: docker/login-action@v3
        with:
          registry: me-west1-docker.pkg.dev
          username: _json_key
          password: ${{  secrets.GCP_CREDENTIALS }}
      
      - name: Push to Docker registry
        run: |
          docker push $IMAGE:$TAG
          if ${{ github.ref == 'ref/heads/main' }}; then
            docker push $IMAGE:latest
          fi
      - name: Create git tag
        id: create_git_tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_sha: ${{ inputs.ref }}
          custom_tag: ${{ env.TAG }}
          tag_prefix: ""
